spring:
  datasource:
    url: jdbc:postgresql://localhost:5441/postgres
    username: postgres
    password: postgres
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com
  jpa:
    hibernate:
      ddl-auto: validate


server:
  error:
    include-message: always


logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.web.servlet: DEBUG
#    org.springframework.security: DEBUG